version: '3.7'
services:
  db:
    restart: always
    image: mysql:5.7
    container_name: album_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4306:3306

  web:
    stdin_open: true
    tty: true
    build: .
    container_name: album
    command: bash -c "rm -f tmp/pids/server.pid &&
                      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/memopic
    ports:
      - 3000:3000
    depends_on:
      - db
